version: '3.7'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - "${PORT}:3000"
    env_file:
      - .env
    environment:
      - MONGO_HOST=mongodb
  mongodb:
    image: mongo:5
    restart: unless-stopped
    container_name: mongodb
    volumes:
      - /data/mongodb:/data/db
    ports:
      - "${MONGO_PORT}:27017"
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
